<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'cache' => 'get1',
  'view' => 'get2',
  'flash' => 'get3',
  'audit' => 'get4',
  'log' => 'get5',
  'sqllogger' => 'get6',
  'csrf' => 'get7',
  'debugstack' => 'get8',
  'debugsqllogger' => 'get9',
  'security' => 'get10',
  'profile' => 'get11',
  'language' => 'get12',
  'timer' => 'get13',
  'session' => 'get14',
  'budget' => 'get15',
  'cash_advance' => 'get16',
  'emp_expense' => 'get17',
  'emp_expense_category' => 'get18',
  'emp_expense_subcategory' => 'get19',
  'employee' => 'get20',
  'employee_position' => 'get21',
  'machine' => 'get22',
  'machine_brand' => 'get23',
  'machine_category' => 'get24',
  'office_department' => 'get25',
  'user_account' => 'get26',
  'userlevelpermissions' => 'get27',
  'userlevels' => 'get28',
  'cash_advance_request' => 'get29',
  'homepage' => 'get30',
  'pending_expense' => 'get31',
  'man_expense' => 'get32',
  'man_expense_category' => 'get33',
  'man_expense_subcategory' => 'get34',
  'yesterday' => 'get35',
  'weekly' => 'get36',
  'monthly' => 'get37',
  'todayy' => 'get38',
  'ExpenseYesterday' => 'get39',
  'ExpenseToday' => 'get40',
  'ExpenseMonthly' => 'get41',
  'ExpenseWeekly' => 'get42',
  'Dashboard2' => 'get43',
  'summary' => 'get44',
  'employeemonthlyexpense' => 'get45',
  'EmpMonthlyExpense' => 'get46',
  'manmonthlyexpense' => 'get47',
  'ManagerMonthlyExpense' => 'get48',
  'utilities' => 'get49',
  'UtilitiesExpense' => 'get50',
  'machinerepairhistory2' => 'get51',
  'MachineRepairHistory' => 'get52',
  'EmployeeDashboard2' => 'get53',
  'EmployeeDashboarddd' => 'get54',
  'usertable' => 'get55',
);

    protected function get1()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\HttpCache\CacheProvider();
    }, 'cache');
    }

    protected function get2()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\Views\PhpRenderer("views/");
    }, 'view');
    }

    protected function get3()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\Flash\Messages();
    }, 'flash');
    }

    protected function get4()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $logger = new \Monolog\Logger("audit"); // For audit trail
        $logger->pushHandler(new \PHPMaker2022\efga_expense_system\AuditTrailHandler("audit.log"));
        return $logger;
    }, 'audit');
    }

    protected function get5()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        global $RELATIVE_PATH;
        $logger = new \Monolog\Logger("log");
        $logger->pushHandler(new \Monolog\Handler\RotatingFileHandler($RELATIVE_PATH . "log.log"));
        return $logger;
    }, 'log');
    }

    protected function get6()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $loggers = [];
        if (\PHPMaker2022\efga_expense_system\Config("DEBUG")) {
            $loggers[] = $c->get("debugstack");
        }
        return (count($loggers) > 0) ? new \Doctrine\DBAL\Logging\LoggerChain($loggers) : null;
    }, 'sqllogger');
    }

    protected function get7()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        global $ResponseFactory;
        return new \Slim\Csrf\Guard($ResponseFactory, \PHPMaker2022\efga_expense_system\Config("CSRF_PREFIX"));
    }, 'csrf');
    }

    protected function get8()
    {
        $object = new Doctrine\DBAL\Logging\DebugStack();
        return $object;
    }

    protected function get9()
    {
        $object = new PHPMaker2022\efga_expense_system\DebugSqlLogger();
        return $object;
    }

    protected function get10()
    {
        $object = new PHPMaker2022\efga_expense_system\AdvancedSecurity();
        return $object;
    }

    protected function get11()
    {
        $object = new PHPMaker2022\efga_expense_system\UserProfile();
        return $object;
    }

    protected function get12()
    {
        $object = new PHPMaker2022\efga_expense_system\Language();
        return $object;
    }

    protected function get13()
    {
        $object = new PHPMaker2022\efga_expense_system\Timer(true);
        return $object;
    }

    protected function get14()
    {
        $object = new PHPMaker2022\efga_expense_system\HttpSession();
        return $object;
    }

    protected function get15()
    {
        $object = new PHPMaker2022\efga_expense_system\Budget();
        return $object;
    }

    protected function get16()
    {
        $object = new PHPMaker2022\efga_expense_system\CashAdvance();
        return $object;
    }

    protected function get17()
    {
        $object = new PHPMaker2022\efga_expense_system\EmpExpense();
        return $object;
    }

    protected function get18()
    {
        $object = new PHPMaker2022\efga_expense_system\EmpExpenseCategory();
        return $object;
    }

    protected function get19()
    {
        $object = new PHPMaker2022\efga_expense_system\EmpExpenseSubcategory();
        return $object;
    }

    protected function get20()
    {
        $object = new PHPMaker2022\efga_expense_system\Employee();
        return $object;
    }

    protected function get21()
    {
        $object = new PHPMaker2022\efga_expense_system\EmployeePosition();
        return $object;
    }

    protected function get22()
    {
        $object = new PHPMaker2022\efga_expense_system\Machine();
        return $object;
    }

    protected function get23()
    {
        $object = new PHPMaker2022\efga_expense_system\MachineBrand();
        return $object;
    }

    protected function get24()
    {
        $object = new PHPMaker2022\efga_expense_system\MachineCategory();
        return $object;
    }

    protected function get25()
    {
        $object = new PHPMaker2022\efga_expense_system\OfficeDepartment();
        return $object;
    }

    protected function get26()
    {
        $object = new PHPMaker2022\efga_expense_system\UserAccount();
        return $object;
    }

    protected function get27()
    {
        $object = new PHPMaker2022\efga_expense_system\Userlevelpermissions();
        return $object;
    }

    protected function get28()
    {
        $object = new PHPMaker2022\efga_expense_system\Userlevels();
        return $object;
    }

    protected function get29()
    {
        $object = new PHPMaker2022\efga_expense_system\CashAdvanceRequest();
        return $object;
    }

    protected function get30()
    {
        $object = new PHPMaker2022\efga_expense_system\Homepage();
        return $object;
    }

    protected function get31()
    {
        $object = new PHPMaker2022\efga_expense_system\PendingExpense();
        return $object;
    }

    protected function get32()
    {
        $object = new PHPMaker2022\efga_expense_system\ManExpense();
        return $object;
    }

    protected function get33()
    {
        $object = new PHPMaker2022\efga_expense_system\ManExpenseCategory();
        return $object;
    }

    protected function get34()
    {
        $object = new PHPMaker2022\efga_expense_system\ManExpenseSubcategory();
        return $object;
    }

    protected function get35()
    {
        $object = new PHPMaker2022\efga_expense_system\Yesterday();
        return $object;
    }

    protected function get36()
    {
        $object = new PHPMaker2022\efga_expense_system\Weekly();
        return $object;
    }

    protected function get37()
    {
        $object = new PHPMaker2022\efga_expense_system\Monthly();
        return $object;
    }

    protected function get38()
    {
        $object = new PHPMaker2022\efga_expense_system\Todayy();
        return $object;
    }

    protected function get39()
    {
        $object = new PHPMaker2022\efga_expense_system\ExpenseYesterday();
        return $object;
    }

    protected function get40()
    {
        $object = new PHPMaker2022\efga_expense_system\ExpenseToday();
        return $object;
    }

    protected function get41()
    {
        $object = new PHPMaker2022\efga_expense_system\ExpenseMonthly();
        return $object;
    }

    protected function get42()
    {
        $object = new PHPMaker2022\efga_expense_system\ExpenseWeekly();
        return $object;
    }

    protected function get43()
    {
        $object = new PHPMaker2022\efga_expense_system\Dashboard2();
        return $object;
    }

    protected function get44()
    {
        $object = new PHPMaker2022\efga_expense_system\Summary();
        return $object;
    }

    protected function get45()
    {
        $object = new PHPMaker2022\efga_expense_system\Employeemonthlyexpense();
        return $object;
    }

    protected function get46()
    {
        $object = new PHPMaker2022\efga_expense_system\EmpMonthlyExpense();
        return $object;
    }

    protected function get47()
    {
        $object = new PHPMaker2022\efga_expense_system\Manmonthlyexpense();
        return $object;
    }

    protected function get48()
    {
        $object = new PHPMaker2022\efga_expense_system\ManagerMonthlyExpense();
        return $object;
    }

    protected function get49()
    {
        $object = new PHPMaker2022\efga_expense_system\Utilities();
        return $object;
    }

    protected function get50()
    {
        $object = new PHPMaker2022\efga_expense_system\UtilitiesExpense();
        return $object;
    }

    protected function get51()
    {
        $object = new PHPMaker2022\efga_expense_system\Machinerepairhistory2();
        return $object;
    }

    protected function get52()
    {
        $object = new PHPMaker2022\efga_expense_system\MachineRepairHistory();
        return $object;
    }

    protected function get53()
    {
        $object = new PHPMaker2022\efga_expense_system\EmployeeDashboard2();
        return $object;
    }

    protected function get54()
    {
        $object = new PHPMaker2022\efga_expense_system\EmployeeDashboarddd();
        return $object;
    }

    protected function get55()
    {
        return $this->delegateContainer->get('user_account');
    }

}
